window.defaultMachines = [
    { model: 'A', img: 'img/ImagenMaquina1.jpg', title: 'Combo de máquinas mecatrónicas marca Kansew', desc: 'Plana, fileteadora, y recubridora.<br>Nuevas o de segunda.<br>Garantía 15 meses nueva en defecto de fábrica.<br>Garantía 8 meses segunda en defecto de fábrica.<br>', price: 'Sujeto a variedad de precio' },
    { model: 'B', img: 'img/ImagenMaquina2.jpg', title: 'Combo de máquinas mecatrónicas industriales marca Jack', desc: 'Plana, fileteadora y recubridora.<br>Nuevas o de segunda.<br>Garantía 15 meses nueva en defecto de fábrica.<br>Garantía 8 meses segunda en defecto de fábrica.<br>', price: 'Sujeto a variedad de precio' },
    { model: 'C', img: 'img/ImagenMaquina3.jpg', title: 'Máquina Modelo C', desc: 'Cuenta con panel diseñado inteligentemente.<br>Cuenta con una leva de hilo integrado y una precisión de mecanizado avanzado.<br>cuenta con una luz LED ajustable<br>El panel utiliza un servomotor ZWB<br>cuenta con cuchilla para corte al lado izquierdo.<br>Número de agujas: 3<br>Número de hilos: 5<br>Altura de elevación del prénsatelas: 1.5-4.5mm<br>Velocidad máxima: 4000 rpm<br>', price: 'Precio: $' },
    { model: 'D', img: 'img/ImagenMaquina4.jpg', title: 'Máquina Cuchilla Izquierda Jack K5-UT-35AC', desc: 'Tiene un rango de costura amplio.<br>cuenta con una voz que puede recordar operaciones o avisar sobre errores.<br>Totalmente sellada para evitar fugas de aceite y no deja manchas en la tela.<br>Velocidad máxima: 5500 rpm.<br>', price: 'Precio: $1,800' },
    { model: 'E', img: 'img/ImagenMaquina5.jpg', title: 'Máquina Recubridora Jack W4', desc: 'Características máquina recubridora mecatrónica Jack W4 especial para collarín, potencia 550W, 110V.', price: 'Sujeto a variedad de precio' },
    { model: 'F', img: 'img/ImagenMaquina6.jpg', title: 'Máquina Plana Electrónica Jack A4', desc: 'Características plana electrónica Jack A4, posicionador de aguja, motor Direct Drive, corte de hilo automático, alza pie automático, comando de voz, atraque automático, lampara, USB.', price: 'Precio: $' },
    { model: 'G', img: 'img/ImagenMaquina7.jpg', title: 'Máquina Fileteadora Mecatrónica', desc: 'Características de la máquina Fileteadora Mecatrónica, puntada de seguridad, 5 hilos, 110V.', price: 'Precio: $' },
    { model: 'H', img: 'img/ImagenMaquina8.jpg', title: 'Máquina Plana Electrónica A4b', desc: 'Características de la máquina plana electrónica A4b, puntada recta, panel de control, corte de hebra automático, 110V.', price: 'Precio: $' },
    { model: 'I', img: 'img/ImagenMaquina9.jpg', title: 'Máquina Plana Electrónica Jack A5E', desc: 'Características de la máquina plana electrónica Jack A5E, puntada recta, panel de control, corte de hilo automático, alzador de pie automático, 110V - 220V, tecnología avanzada, facilidad y agilidad para los tipos de trabajos livianos y pesados.', price: 'Precio: $' },
    { model: 'J', img: 'img/ImagenMaquina10.jpg', title: 'Máquina Fileteadora A4s', desc: 'Características de la máquina fileteadora A4s, puntada sencilla, doble diferencial, 1550 (RPM), 110V.', price: 'Precio: $' },
    { model: 'K', img: 'img/ImagenMaquina11.jpg', title: 'Máquina Ojaladora Jack', desc: 'Características de la máquina Ojaladora Jack mecatrónica, de un solo pedal, en su funcionamiento cuando para alza el pie automático, tiene tijera incorporada, con corte de hebra en superior e inferior, 3600 (RPM), posicionador de aguja.', price: 'Precio: $' },
    { model: 'L', img: 'img/ImagenMaquina12.jpg', title: 'Máquina Electrónica Jack Fileteadora C4', desc: 'Características de la máquina electrónica Jack fileteadora C4, industrial, puntada de seguridad, panel de control en cabezal, 220V, potencia 550W.', price: 'Precio: $' }
];
